#!/usr/bin/env python
# coding: utf-8

import sys
import getpass
import getopt
import hashlib
import base64
if sys.platform == "linux":
    import pygtk
    import gtk

def pwget(username, domain, masterPassword):
    password = hashlib.sha1()
    password.update(username)
    password.update(domain)
    password.update(masterPassword)
    sha1hash = password.hexdigest()
    encodedHash = base64.b64encode(sha1hash)
    return encodedHash[:20]

def usage():
    print "define username, domain name and master-password"

def main(argv):
    username = ""
    domain = ""
    try:
        opts, args = getopt.gnu_getopt(argv, "hu:d:", ["help", "username", "domain"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        if opt in ("-u", "--username"):
            username = arg
        if opt in ("-d", "--domain"):
            domain = arg
    masterPassword = getpass.getpass()

    if masterPassword and username and domain:
        password = pwget(username, domain, masterPassword)
        if sys.platform == "linux":
            clipboard = gtk.clipboard_get()
            clipboard.set_text(password)
            clipboard.store() # don't get why this is not working
            raw_input("Press any key to continue…") # clipboard able to use when program is working
        elif sys.platform == "darwin":
            print password
        return password
    else:
        usage()
        sys.exit()

if __name__ == "__main__":
    main(sys.argv[1:])
