#!/usr/bin/env python
# coding: utf-8

import sys
import getpass
import os
import getopt
import hashlib
import base64
import ConfigParser
if sys.platform == "linux2":
    import pygtk
    import gtk

loginPairs = {}
def parseConfig():
    config = ConfigParser.ConfigParser()
    config.read(os.environ["HOME"] + "/.pwget.ini")

    siteSection = "sites"
    if config.has_section(siteSection):
        for option in config.options(siteSection):
            loginPairs[option] = config.get(siteSection, option)

def pwget(username, domain, masterPassword):
    password = hashlib.sha1()
    password.update(username)
    password.update(domain)
    password.update(masterPassword)
    sha1hash = password.hexdigest()
    encodedHash = base64.b64encode(sha1hash)
    return encodedHash[:20]

def usage():
    print "define username, domain name and master-password"

def main(argv):
    parseConfig()

    username = ""
    domain = ""
    try:
        opts, args = getopt.gnu_getopt(argv, "hu:d:", ["help", "username", "domain"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        if opt in ("-u", "--username"):
            username = arg
        if opt in ("-d", "--domain"):
            domain = arg
    if domain:
        masterPassword = getpass.getpass()

        if masterPassword and domain:
            if username == "":
                username = loginPairs[domain]
            password = pwget(username, domain, masterPassword)
            if sys.platform == "linux2":
                clipboard = gtk.clipboard_get()
                clipboard.set_text(password)
                clipboard.store() # don't get why this is not working
                raw_input("Press `Enter` to continue…") # clipboard able to use when program is working
            elif sys.platform == "darwin":
                print password
            return password
        else:
            usage()
            sys.exit()

if __name__ == "__main__":
    main(sys.argv[1:])
