#!/usr/bin/env python
# coding: utf-8

import sys
import getpass
import os
import getopt
import hashlib
import base64
import ConfigParser
if sys.platform == "linux2":
    import pygtk
    import gtk

config = ConfigParser.ConfigParser()
config.read(os.environ["HOME"] + "/.pwget.ini")

def pwget(username, domain, masterPassword):
    password = hashlib.sha1()
    password.update(username)
    password.update(domain)
    password.update(masterPassword)
    sha1hash = password.hexdigest()
    encodedHash = base64.b64encode(sha1hash)
    return encodedHash[:20]

def usage():
    print "define username, domain name and master-password"

def main(argv):
    username = ""
    domain = ""
    try:
        opts, args = getopt.gnu_getopt(argv, "hu:d:", ["help", "username", "domain"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        if opt in ("-u", "--username"):
            username = arg
        if opt in ("-d", "--domain"):
            domain = arg
    if domain:
        if username == "":
            if config.has_section("sites") and config.has_option("sites", domain):
                username = config.get("sites", domain)
        if username and domain:
            masterPassword = getpass.getpass()
        else:
            usage()
            sys.exit()
        password = pwget(username, domain, masterPassword)
        if sys.platform == "linux2":
            clipboard = gtk.clipboard_get()
            clipboard.set_text(password)
            clipboard.store() # don't get why this is not working
            raw_input("Press `Enter` to continue…") # clipboard able to use when program is working
        elif sys.platform == "darwin":
            print password
        return password
    else:
        usage()
        sys.exit()

if __name__ == "__main__":
    main(sys.argv[1:])
