#!/bin/bash

CONFIG="$XDG_CONFIG_HOME/rndy/rndyrc"

echo "Rndy was started first time. Do you want to create configuration file? (Y/n)"

read -n 1 -s YES_OR_NO

function setMasterPassword {
    cp /usr/share/rndy/example/rndyrc $CONFIG
    echo "Set master password:"
    read -s MASTERPASSWORD
    tmp=$(mktemp)
    echo -n $MASTERPASSWORD > $tmp
    echo $tmp
    echo "Already use GPG? (Y/n)"
    read -n 1 -s YES_OR_NO
    if [[ $YES_OR_NO != 'n' ]]; then
        encryptMasterPassword
    else
        installGpgKey
    fi
    exit
}

function installGpgKey {
    echo "Not implemented"
    exit
}

function encryptMasterPassword {
    gpg -o $XDG_CONFIG_HOME/rndy/rndypassword.gpg -e $tmp
    rm $tmp
    exit
}

if [[ $YES_OR_NO != 'n' ]]; then
    touch $CONFIG

    echo "Use GPG? (Y/n)"
    read -n 1 -s YES_OR_NO
    if [[ $YES_OR_NO != 'n' ]]; then
        setMasterPassword
    else
        exit 0
    fi
else
    exit 0
fi
